In [1]:
import numpy as np

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[6]

np.int64(17)

In [7]:
arr[1:4]

array([12, 13, 14])

In [8]:
arr[:4]

array([11, 12, 13, 14])

In [9]:
arr[4:]

array([15, 16, 17, 18, 19, 20])

In [10]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr[0,1])
print(arr[1,2])

2
6


In [11]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [13]:
arr[5]

array([26, 27, 28, 29, 30])

In [14]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [15]:
arr[0,0]

np.int64(1)

In [16]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [18]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [19]:
import numpy as np

arr= np.array([10, 20, 30, 40, 50])

print(arr[arr > 30])

[40 50]


In [20]:
arr == 20

array([False,  True, False, False, False])

In [21]:
print(arr[arr == 30])

[30]


In [22]:
print(arr[arr <= 20])

[10 20]


In [23]:
arr <= 20


array([ True,  True, False, False, False])