In [5]:
import numpy as np


In [6]:
arr = np.array([10,11,12,13,14])
arr

array([10, 11, 12, 13, 14])

In [7]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Create two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
# Add the two arrays
result = arr1 + arr2
print(result)

[ 7  9 11 13 15]


In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
import numpy as np

np.array([1,2,3])            # Create array
np.zeros((2,3))              # All zeros
np.ones((2,3))               # All ones
np.full((2,2),7)             # Fill with 7
np.eye(3)                    # Identity matrix
np.arange(1,10,2)            # Sequence with step
np.linspace(0,1,5)           # Evenly spaced values
np.random.rand(3)            # Random decimals
np.random.randint(1,10,5)    # Random integers
np.empty((2,2))              # Empty Array.ipynb

array([[3.5e-323, 3.5e-323],
       [3.5e-323, 3.5e-323]])

In [11]:
np.arange(1,10,2)            

array([1, 3, 5, 7, 9])

In [12]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
print(arr1.size)

5


In [14]:
np.random.rand(5)


array([0.51985422, 0.1528954 , 0.55359002, 0.64683192, 0.79651415])

In [16]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [17]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [18]:
arr.resize()
