In [10]:
import numpy as np

In [110]:
# Create a 1D NumPy array containing numbers from 1 to 10.
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Create a 3×3 array filled with zeros.
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# Create a 4×4 array filled with ones.
arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
# Create an identity matrix of size 5×5.
arr = np.array((5,5))
arr.size

2

In [31]:
arr = np.array((5,5))
arr.size

2

In [32]:
# Create an array using arange() from 10 to 50 with a step of 5.
arr = np.arange(10,51,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [34]:
# Create 10 equally spaced numbers between 0 and 1 using linspace().
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [38]:
# Generate a 3×3 array of random integers between 1 and 100.
arr = np.random.randint(1, 101, (3,3))
arr

array([[36,  9,  5],
       [22, 90, 38],
       [28, 69, 14]], dtype=int32)

In [41]:
# Create a 2×3 array filled with the value 7.
arr = np.full((2,3), 7)
arr

array([[7, 7, 7],
       [7, 7, 7]])

In [48]:
# Find the shape, size, ndim, and dtype of a given array
arr = np.array([[11,12,13], [14,15,16]])
print("Array", arr)
print("Shape", arr.shape)
print("Size", arr.size)
print("Dimention", arr.ndim)
print("Data Type", arr.dtype)

Array [[11 12 13]
 [14 15 16]]
Shape (2, 3)
Size 6
Dimention 2
Data Type int64


In [49]:
# Find the memory occupied by an array using nbytesabs
arr = np.array([[11,12,13], [14,15,16]])
arr.nbytes

48

In [50]:
# Find the size of each element using itemsize.
arr = np.array([[11,12,13], [14,15,16]])
arr.itemsize

8

In [57]:
# Check whether an array is 1D or 2D.
arr = np.array([[11,12,13], [14,15,16], [11,12,13]])
if arr.ndim == 1:
    print("The array is 1D.")
elif arr.ndim == 2:
    print("The array is 2D.")
else:
    print("The array has", arr.ndim, "dimensions.")

The array is 2D.


In [59]:
# Create a float array and check its data type.
arr = np.array([[11,12,13], [14,15,16], [1.1,1.2,1.1]])
arr.dtype

dtype('float64')

In [61]:
# Print the first and last element of an array.
arr = np.array([11, 12, 13, 14, 15, 16])
print("Starting", arr[0])
print("Last", arr[-1])

Starting 11
Last 16


In [65]:
# Print all even-index elements from an array
arr = np.array([10, 20, 30, 40, 50, 60, 70])
arr[::2]

array([10, 30, 50, 70])

In [68]:
# Reverse an array using slicing
arr = np.array([10, 20, 30, 40, 50, 60, 70])
arr[::-1]


array([70, 60, 50, 40, 30, 20, 10])

In [74]:
# Print the second row of a 2D array.abs
arr = np.array([[10, 20, 30], [40, 50, 60]])
arr[1:]

array([[40, 50, 60]])

In [80]:
# Print the third column of a 2D array.
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr[:,2]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [85]:
# Extract the middle 3 elements from a 1D array.
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr[:,1]


array([20, 50, 80])

In [88]:
# Print all elements greater than 50.
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr[arr > 50]

array([60, 70, 80, 90])

In [90]:
# Print all even numbers from an array.
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 99, 90]])
arr[arr % 2 == 0]

array([10, 20, 30, 40, 50, 60, 70, 90])

In [93]:
# Replace all negative numbers with 0 using Boolean indexing.
arr = np.array([[-10, 20, 30], [40, -50, 60], [70, 99, -90]])
arr[arr < 0] = 0
arr

array([[ 0, 20, 30],
       [40,  0, 60],
       [70, 99,  0]])

In [96]:
# Print elements that are greater than 20 and less than 60.
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr[(arr >  20) & (arr < 60)]

array([30, 40, 50])

In [99]:
# Convert a 1D array of 12 elements into a 3×4 matrix.
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
# Transpose a 3×3 matrix.
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original", arr)
print("Transpose", arr.T)

Original [[10 20 30]
 [40 50 60]
 [70 80 90]]
Transpose [[10 40 70]
 [20 50 80]
 [30 60 90]]


In [109]:
# Reshape an array using -1.
arr = np.arange(1, 13)
new_arr = arr.reshape(2, -1)
new_arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [111]:
# Add two arrays element-wise.
arr1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
ans = arr1 + arr2
ans

array([[ 20,  40,  60],
       [ 80, 100, 120],
       [140, 160, 180]])

In [112]:
# Multiply two arrays element-wise.
arr1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
ans = arr1 * arr2
ans

array([[ 100,  400,  900],
       [1600, 2500, 3600],
       [4900, 6400, 8100]])

In [113]:
# Find the dot product of two arrays.
arr1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
ans = np.dot(arr1, arr2)
ans

array([[ 3000,  3600,  4200],
       [ 6600,  8100,  9600],
       [10200, 12600, 15000]])

In [114]:
# Add 10 to every element using broadcasting.
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
result = arr + 10
result

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

In [123]:
# Find the square root of every element in an array.
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
np.square(arr)

array([[ 100,  400,  900],
       [1600, 2500, 3600],
       [4900, 6400, 8100]])

In [125]:
# Find the sum, mean, median, maximum, and minimum of an array.
arr = np.array([10, 20, 30, 40, 50])
print("Sum    :", np.sum(arr))
print("Mean   :", np.mean(arr))
print("Median :", np.median(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Sum    : 150
Mean   : 30.0
Median : 30.0
Maximum: 50
Minimum: 10


In [126]:
# Find the index of the maximum and minimum values.
arr = np.array([15, 40, 25, 80, 35])
print("Maximum:", np.argmax(arr))
print("Minimum:", np.argmin(arr))

Maximum: 3
Minimum: 0


In [127]:
# Calculate the standard deviation and variance of an array.
arr = np.array([10, 20, 30, 40, 50])
print("Standard Deviation:", np.std(arr))
print("Variance          :", np.var(arr))

Standard Deviation: 14.142135623730951
Variance          : 200.0


In [128]:
# Concatenate two arrays.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate((arr1, arr2))
result

array([1, 2, 3, 4, 5, 6])

In [129]:
# Stack two arrays vertically and horizontally.
# Vertical Stack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.vstack((arr1, arr2))
result



array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
# Horizontal Stack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.hstack((arr1, arr2))
result

array([1, 2, 3, 4, 5, 6])

In [131]:
# Split an array into four equal parts.
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
result = np.split(arr, 4)
result

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]